spring:
  application:
    name: back
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    serialization:
      fail-on-empty-beans: false # 빈 객체 직렬화 시 예외 발생 방지
logging:
  level:
    com:
      back: debug
server:
  port: 8080